name: CI/CD

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose

      - name: Build Code
        run: npm run build:noemit

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose

      - name: Check Formatting
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose

      - name: Lint Code
        run: npm run lint

  publish:
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [ build, format, lint ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose
        
      - name: Build
        run: npm run build:only

      - name: Publish
        run: npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Pack
        run: npm pack --verbose

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tgz,LICENSE,README.md"
          token: ${{ secrets.GITHUB_TOKEN }}

  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ build, format, lint ]
    steps:
      - name: Use NodeJS v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Generate and publish documentation
        env:
          DIRECTORY: "./docs"
        run: |
          gitdir=`mktemp -d`
          moddir=`mktemp -d`
          git clone "https://github.com/$GITHUB_REPOSITORY.git" "$gitdir" --depth=1 --progress --single-branch --verbose
          cd "$gitdir"
          git config advice.detachedHead false
          git checkout --force "$GITHUB_SHA"
          npm ci --verbose
          npm run docs
          mv -vf "$gitdir/$DIRECTORY"/* $moddir
          cd "$moddir"
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          echo "This is an automated branch. Please do not commit to or change any files in it." >> README
          git add . -v
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git branch -m docs
          git commit --verbose -m "
          $GITHUB_SHA
          
          This is an automated commit by a GitHub workflow.
          It contains generated documentation from the main branch of this repository.
          Action: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          "
          git push origin docs --force --verbose
          cd ~
          rm -rf "$gitdir"
          rm -rf "$moddir"
